### PR TITLE
fix: update vue-shims for Vue v3.0.1

### LINKED ISSUE #5974: Vue 3 initial unit test does not work: Property "msg" was accessed during render but is not defined on instance.
### Version
3.0.0

### Reproduction link
[https://github.com/E-jarod/vue3-test.git](https://github.com/E-jarod/vue3-test.git)

### Steps to reproduce
Hello, I have simply created a new Vue 3.0.0 (`vue create vue3-test`) project with the following preset :
**`~/.vuerc`**
```json
{
  ...
  "presets": {
    "personal-basic-vue3": {
      "useConfigFiles": true,
      "plugins": {
        "@vue/cli-plugin-babel": {},
        "@vue/cli-plugin-typescript": {
          "classComponent": true,
          "useTsWithBabel": true
        },
        "@vue/cli-plugin-router": {
          "historyMode": true
        },
        "@vue/cli-plugin-eslint": {
          "config": "prettier",
          "lintOn": [
            "save",
            "commit"
          ]
        },
        "@vue/cli-plugin-unit-jest": {},
        "@vue/cli-plugin-e2e-cypress": {}
      },
      "vueVersion": "3",
      "cssPreprocessor": "dart-sass"
    }
  }
}
```

I come from angular and I am new to Vue. Everything else works fine, but not the jest unit test.

You can see on my github repo.

### What is expected?
The jest test should at least works, because it is the starter project.

### What is actually happening?
And when I run :
```bash
yarn test:unit
# or
npm run test:unit
```

I get the following Error
```bash
❯ y test:unit
yarn run v1.22.5
$ vue-cli-service test:unit
 FAIL  tests/unit/example.spec.ts
  ● Test suite failed to run

    TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
    tests/unit/example.spec.ts:7:34 - error TS2769: No overload matches this call.
      The last overload gave the following error.
        Argument of type 'DefineComponent<{}, {}, {}, Record<string, ComputedGetter<any> | WritableComputedOptions<any>>, MethodOptions, ComponentOptionsMixin, ... 5 more ..., {}>' is not assignable to parameter of type 'ComponentOptionsWithObjectProps<readonly string[] | Readonly<ComponentObjectPropsOptions<Record<string, unknown>>>, {}, {}, Record<string, ComputedGetter<any> | WritableComputedOptions<...>>, ... 6 more ..., { ...; } | {}>'.
          Property 'props' is missing in type 'ComponentPublicInstanceConstructor<{ $: ComponentInternalInstance; $data: {}; $props: Partial<{}> & Pick<Readonly<{} & {}> & VNodeProps & AllowedComponentProps & ComponentCustomProps, "key" | ... 8 more ... | "style">; ... 10 more ...; $watch(source: string | Function, cb: Function, options?: WatchOptions<...> | und...' but required in type '{ props: (readonly string[] & ThisType<void>) | (Readonly<ComponentObjectPropsOptions<Record<string, unknown>>> & ThisType<void>); }'.

    7     const wrapper = shallowMount(HelloWorld, {
                                       ~~~~~~~~~~

      node_modules/@vue/runtime-core/dist/runtime-core.d.ts:336:5
        336     props: PropsOptions & ThisType<void>;
                ~~~~~
        'props' is declared here.
      node_modules/@vue/test-utils/dist/mount.d.ts:36:25
        36 export declare function mount<PropsOptions extends Readonly<ComponentPropsOptions>, RawBindings, D, C extends ComputedOptions = {}, M extends Record<string, Function> = {}, E extends EmitsOptions = Record<string, any>, Mixin extends ComponentOptionsMixin = ComponentOptionsMixin, Extends extends ComponentOptionsMixin = ComponentOptionsMixin, EE extends string = string>(componentOptions: ComponentOptionsWithObjectProps<PropsOptions, RawBindings, D, C, M, E, Mixin, Extends, EE>, options?: MountingOptions<ExtractPropTypes<PropsOptions>, D>): VueWrapper<ComponentPublicInstance<ExtractPropTypes<PropsOptions>, RawBindings, D, C, M, E, VNodeProps & ExtractPropTypes<PropsOptions>>>;
                                   ~~~~~
        The last overload is declared here.

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.526s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
---
Can you detail why this is happening ?

### PR DESCRIPTION
**Pull request by cexbrayat**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Underlying tools
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Other information:**
https://github.com/vuejs/vue-next/commit/6aa2256913bfd097500aba83b78482b87107c101 intriduced a change in `DefineComponent` type, that results in a broken bare CLI app that would use VTU, as `mount` will not compile.

This relaxes the type definitation by using generic `any`.

Fixes #5974

### CODE REVIEW

**Review by rayfoss — APPROVED** [review]
It works. This seems like a reasonable compromise for now... there may be a case for defining types at a per component level down the road...

File: packages/@vue/cli-plugin-typescript/generator/template-vue3/src/shims-vue.d.ts [hunk 1]
```diff
@@ -1,5 +1,5 @@
 declare module '*.vue' {
   import type { DefineComponent } from 'vue'
-  const component: DefineComponent
+  const component: DefineComponent<any, any, any>
```
Comment (pikax) [inline packages/@vue/cli-plugin-typescript/generator/template-vue3/src/shims-vue.d.ts:3]: Overriding props should be enough. 

```ts
DefineComponent<any>
```

Comment (pikax) [inline packages/@vue/cli-plugin-typescript/generator/template-vue3/src/shims-vue.d.ts:3]: `DefineComponent<{}, {}, any>`

maybe?

Comment (cexbrayat) [reply packages/@vue/cli-plugin-typescript/generator/template-vue3/src/shims-vue.d.ts]: 👍 Yes, now that VTU beta.7 is out, this is enough.

**Comment by cexbrayat** [comment]
I updated the PR to use `const component: DefineComponent<{}, {}, any>` which is now enough to fix the issue with VTU 2.0.0-beta.7 out.

**Review by pikax — APPROVED** [review]

**Comment by sodatea** [comment]
Thanks!

**Comment by alperkay** [comment]
I just created an app with vue/cli v4.5.8 . It looks like it uses Vue v3.0.2 and Vue Test Utils v2.0.0-beta.7 and I'm still having the same issue when I run the default unit test. The exact error is as follows:

```
[Vue warn]: Property "msg" was accessed during render but is not defined on instance.
      at <Anonymous msg="new message" ref="VTU_COMPONENT" >
      at <VTUROOT> 
```

Any idea?

**Comment by awerlang** [comment]
@alperkay that's a different matter. This PR targets a typing (i.e. compile-time) issue, yours is a runtime issue (missing prop declaration?)
