### PR TITLE
Require.resolve fallback on node < 8.10.0

### LINKED ISSUE #1396: vue create node under v8.10.0: Error: Failed to resolve plugin: @vue/cli-service
### Version
3.0.0-beta.14

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Steps to reproduce
`npm i -g @vue/cli` or `yarn add global @vue/cli`.
Then run `vue create <project-name>` and select default settings.

### What is expected?
Command to scaffold  project and install dependencies.

### What is actually happening?
Command creates `package.json`,  `package-lock.json` files and installs some (or all?) dependencies into `node_modules` dir, but doesn't scaffold any other files.

It fails with error:

```
🚀  Invoking generators...
 ERROR  Error: Failed to resolve plugin: @vue/cli-service
Error: Failed to resolve plugin: @vue/cli-service
    at Creator.resolvePlugins (/Users/ziga/.nvm/versions/node/v8.9.4/lib/node_modules/@vue/cli/lib/Creator.js:303:15)
    at Creator.create (/Users/ziga/.nvm/versions/node/v8.9.4/lib/node_modules/@vue/cli/lib/Creator.js:146:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

### PR DESCRIPTION
**Pull request by Akryum**
Fix #1396

### CODE REVIEW

File: packages/@vue/cli/lib/util/nodeVersion.js [hunk 1]
```diff
@@ -0,0 +1,5 @@
+exports.minNode = function (major, minor = 0, patch = 0) {
+  const parts = process.versions.node.split('.').map(v => parseInt(v))
+  if (parts[0] >= major && parts[1] >= minor && parts[2] >= patch) return true
```
Comment (zigomir) [inline packages/@vue/cli/lib/util/nodeVersion.js]: could return whole expression

File: packages/@vue/cli/lib/util/nodeVersion.js [hunk 2]
```diff
@@ -0,0 +1,5 @@
+exports.minNode = function (major, minor = 0, patch = 0) {
+  const parts = process.versions.node.split('.').map(v => parseInt(v))
```
Comment (zigomir) [inline packages/@vue/cli/lib/util/nodeVersion.js]: could use destructuring and give part names like const [major,minor,patch] = ...

i’m aware these are already taken, just suggesting.

File: packages/@vue/cli/lib/util/module.js [hunk 3]
```diff
@@ -1,7 +1,39 @@
...
+    const lookupPaths = Module._resolveLookupPaths(request, fakeParent, true)
+
+    if (!paths.includes(path)) paths.push(path)
+
+    for (var j = 0; j < lookupPaths.length; j++) {
+      if (!paths.includes(lookupPaths[j])) paths.push(lookupPaths[j])
+    }
+  }
+
+  var filename = Module._findPath(request, paths, isMain)
```
Comment (zigomir) [inline packages/@vue/cli/lib/util/module.js]: Why is this var while others are const?

File: packages/@vue/cli/lib/util/module.js [hunk 4]
```diff
@@ -1,7 +1,39 @@
...
+  if (!filename) {
+    var err = new Error(`Cannot find module '${request}'`)
```
Comment (zigomir) [inline packages/@vue/cli/lib/util/module.js]: same as above
