### PR TITLE
fix(build): demo-lib.html compatible Vue 3

### LINKED ISSUE #6216: vue-cli-service build --target lib demo.html still in version 2
### Version
4.5.9

### Environment info
```
MasOS, VueNext
```

### Steps to reproduce
When I build via vue-cli, the build create a file demo.html which is still in Version 2. I built my project with Vue-CLI preset Vue3

### What is expected?
demo.html compatible Vue3

### What is actually happening?
demo.html in Vue2

### PR DESCRIPTION
**Pull request by jeneser**
Closes #6216 

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Underlying tools
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Other information:**

### CODE REVIEW

File: packages/@vue/cli-service/lib/commands/build/resolveLibConfig.js [hunk 1]
```diff
@@ -66,6 +69,7 @@ module.exports = (api, { entry, name, formats, filename, 'inline-vue': inlineVue
             inject: false,
             filename: 'demo.html',
             libName,
+            isVue3,
```
Comment (fangbinwei) [inline packages/@vue/cli-service/lib/commands/build/resolveLibConfig.js:72]: I think inject `vueMajor` is better, else we may need `isVue4` `isVue5` in the future

Comment (sodatea) [reply packages/@vue/cli-service/lib/commands/build/resolveLibConfig.js:72]: And we can use this version string in the unpkg link.

Comment (jeneser) [reply packages/@vue/cli-service/lib/commands/build/resolveLibConfig.js:72]: Nice tips.

**Review by fangbinwei — APPROVED** [review]
