### PR TITLE
Use a single websocket connection for HMR

### LINKED ISSUE #4947: webpack-dev-server/client is loaded twice
### Version

4.1.1

### Environment info

```
$ vue info

Environment Info:

  System:
    OS: Windows 10 10.0.18362
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  4.1.1
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.1.1
    @vue/cli-plugin-babel: ^4.1.0 => 4.1.1
    @vue/cli-plugin-eslint: ^4.1.0 => 4.1.1
    @vue/cli-plugin-router:  4.1.1
    @vue/cli-plugin-vuex:  4.1.1
    @vue/cli-service: ^4.1.0 => 4.1.1
    @vue/cli-shared-utils:  4.1.1
    @vue/component-compiler-utils:  3.1.0
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.2.3
    vue: ^2.6.10 => 2.6.10
    vue-eslint-parser:  5.0.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.7.2
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: (Not Found) 4.1.1

```

### Steps to reproduce

Create a new Vue app using `vue create`, start it using `yarn serve` and open it in the browser.

### What is expected?

`webpack-dev-server/client` is loaded once.

### What is actually happening?

`webpack-dev-server/client` is loaded twice.

### Details

As you can see in the screenshot below, `sockjs-node/info` is loaded twice, and there are two opened websocket connections, one from `localhost` and the other from the machine's IP `192.168.1.4`:

image

Looking at the generated bundle `app.js`, we can see that `webpack-dev-server/client` is loaded twice:
```js
// http://localhost:8080/js/app.js
// ...
__webpack_require__(/*! D:\work\cs-vue-cli-4\node_modules\webpack-dev-server\client\index.js?http://localhost */"./node_modules/webpack-dev-server/client/index.js?http://localhost");
__webpack_require__(/*! D:\work\cs-vue-cli-4\node_modules\webpack\hot\dev-server.js */"./node_modules/webpack/hot/dev-server.js");
__webpack_require__(/*! D:\work\cs-vue-cli-4\node_modules\webpack-dev-server\client\index.js?http://192.168.1.4:8080/sockjs-node */"./node_modules/webpack-dev-server/client/index.js?http://192.168.1.4:8080/sockjs-node");
module.exports = __webpack_require__(/*! ./src/main.js */"./src/main.js");
// ...
```

### Investigation
One of the clients - the second, `webpack-dev-server/client/index.js?http://192.168.1.4:8080/sockjs-node` - is added by `vue-cli-service`'s `serve` command here: https://github.com/vuejs/vue-cli/blob/02f2436bdb44a435122e0de4b3924199b475983e/packages/%40vue/cli-service/lib/commands/serve.js#L145 so the question is, where is the first one `webpack-dev-server/client/index.js?http://localhost` coming from? My first guess was that it was automatically added by `webpack-dev-server`; indeed, going through the docs, I found the [`injectClient`](https://webpack.js.org/configuration/dev-server/#devserverinjectclient) configuration option that specifies whether the dev server should inject the client or not. The weird thing is that the docs say the default value is `false`?!, but let's see what happens if we explicitly set it to `false`. So I added this to `vue.config.js`
```js
// vue.config.js
module.exports = {
  devServer: {
    injectClient: false
  }
}
```
restarted `yarn serve`, and, lo and behold, the client is now only loaded once!

image

```js
// http://localhost:8080/js/app.js
// ...
__webpack_require__(/*! D:\work\cs-vue-cli-4\node_modules\webpack\hot\dev-server.js */"./node_modules/webpack/hot/dev-server.js");
__webpack_require__(/*! D:\work\cs-vue-cli-4\node_modules\webpack-dev-server\client\index.js?http://192.168.1.4:8080/sockjs-node */"./node_modules/webpack-dev-server/client/index.js?http://192.168.1.4:8080/sockjs-node");
module.exports = __webpack_require__(/*! ./src/main.js */"./src/main.js");
// ...
```

My guess is that if `hot` is set to `true` https://github.com/vuejs/vue-cli/blob/02f2436bdb44a435122e0de4b3924199b475983e/packages/%40vue/cli-service/lib/commands/serve.js#L173 the dev server also sets `injectClient` to `true` by default.

### Workaround

Set `devServer.injectClient` to `false` in `vue.config.js`:

```js
// vue.config.js
module.exports = {
  devServer: {
    injectClient: false
  }
}
```

### Fix

(assuming this is considered a bug)

Explicitly set `injectClient` to `false` in the `WebpackDevServer` options https://github.com/vuejs/vue-cli/blob/02f2436bdb44a435122e0de4b3924199b475983e/packages/%40vue/cli-service/lib/commands/serve.js#L164-L166

### PR DESCRIPTION
**Pull request by lbogdan**
Fixes #4947 , see that for details.

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Underlying tools
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

### CODE REVIEW

File: packages/@vue/cli-test-utils/createTestProject.js [hunk 1]
```diff
@@ -17,7 +17,7 @@ module.exports = function createTestProject (name, preset, cwd, initGit = true)
     return fs.existsSync(path.resolve(projectRoot, file))
   }
 
-  if (has(projectRoot)) {
+  if (has(name)) {
```
Comment (lbogdan) [inline packages/@vue/cli-test-utils/createTestProject.js]: I was getting
```
console.warn packages/@vue/cli-test-utils/createTestProject.js:21
    An existing test project already exists for e2e-serve. May get unexpected test results due to project re-use
```
warnings, so I guess this should have been `name` instead?

Comment (lbogdan) [reply packages/@vue/cli-test-utils/createTestProject.js]: Nvm, wrong assumption on my side, the issue seems to be that the test project are not cleaned up after. Should I also fix that in this PR?

**Comment by lbogdan** [comment]
This should be ready for review.

Things I'm not 100% sure:

- how to expose puppeteer's network request URLs to the tests;
- looking at `'sockjs-node'` http requests, which is a `webpack-dev-server` implementation detail. I've tried looking for websocket connections (the http request I look for only returns the websocket options), unfortunately websocket requests don't trigger `page.on('request')`.

File: packages/@vue/cli-test-utils/createTestProject.js (hunk 1 above)
Comment (sodatea) [reply packages/@vue/cli-test-utils/createTestProject.js]: Use a different name for the test project would suffice 😅

Comment (lbogdan) [reply packages/@vue/cli-test-utils/createTestProject.js]: I'm not sure I understand what you mean. 🙂 The issue is that tests create test projects in `packages/test` when they run (e.g. `packages/test/e2e-serve`), which don't get cleaned up, so next time I run tests I get the warning I mentioned above about them already existing:
```
  console.warn packages/@vue/cli-test-utils/createTestProject.js:22
    An existing test project already exists for e2e-serve D:\work\vue-stuff\vue-cli\packages\test\e2e-serve. May get unexpected test results due to project re-use
```

Comment (sodatea) [reply packages/@vue/cli-test-utils/createTestProject.js]: When running tests locally it can be solved by running `yarn clean` first.
The warning in the CI environment is because this test case shares the same project name as the first test case in that file (both are `e2e-serve`).

Comment (lbogdan) [reply packages/@vue/cli-test-utils/createTestProject.js]: Oh, got it, I was talking more about the warnings I got while working on this, I didn't even saw the warning in CI. 🙂 So should I go ahead and change the project name for the test I added?

Comment (sodatea) [reply packages/@vue/cli-test-utils/createTestProject.js]: Yeah I think so

Comment (lbogdan) [reply packages/@vue/cli-test-utils/createTestProject.js]: Sure! Any other feedback, so that I can address everything in a single commit?

Comment (sodatea) [reply packages/@vue/cli-test-utils/createTestProject.js]: The rest of this PR looks pretty good to me 😄
