### PR TITLE
fix(create): fix shouldInitGit check

### LINKED ISSUE #1899: No matter if I activate or deactivate the check box, a git repository is created every time a new project is created.
### Version
3.0.0-rc.5

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Steps to reproduce
1. Open the UI with "vue ui"
2. Create new Project
3. Deactivate Initialize git repository
4. Create Project with any options

### What is expected?
Git repository is not initialized.

### What is actually happening?
.git folder and .gitignore file are created.

### PR DESCRIPTION
**Pull request by sodatea**
closes #1899

### CODE REVIEW

File: packages/@vue/cli/bin/vue.js [hunk 1]
```diff
@@ -49,7 +49,7 @@ program
   .option('-i, --inlinePreset <json>', 'Skip prompts and use inline JSON string as preset')
   .option('-m, --packageManager <command>', 'Use specified npm client when installing dependencies')
   .option('-r, --registry <url>', 'Use specified npm registry when installing dependencies (only for npm)')
-  .option('-g, --git [message]', 'Force / skip git initialization, optionally specify initial commit message')
+  .option('-g, --git [message | false]', 'Force / skip git initialization, optionally specify initial commit message')
```
Comment (Akryum) [inline packages/@vue/cli/bin/vue.js]: I'm not sure `commander` understands this.

**Comment by yyx990803** [comment]
I've changed it to `--no-git` which should no longer be confusing.
