### PR TITLE
Show fallback message for typescript jest preset if ts-jest is not in…

### LINKED ISSUE #6383: @vue/cli-plugin-unit-jest/presets/typescript-and-babel not found
### Version
5.0.0-alpha.8

### Environment info
```
Environment Info:

  System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.15.5/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Edge: 89.0.774.57
    Firefox: 85.0.2
    Safari: 14.0.3
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.2 
    @vue/babel-plugin-jsx:  1.0.3 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  5.0.0-alpha.8 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  5.0.0-alpha.8 
    @vue/cli-plugin-babel: 5.0.0-alpha.8 => 5.0.0-alpha.8 
    @vue/cli-plugin-eslint: 5.0.0-alpha.8 => 5.0.0-alpha.8 
    @vue/cli-plugin-router: 5.0.0-alpha.8 => 5.0.0-alpha.8 
    @vue/cli-plugin-typescript: 5.0.0-alpha.8 => 5.0.0-alpha.8 
    @vue/cli-plugin-unit-jest: ^5.0.0-alpha.8 => 5.0.0-alpha.8 
    @vue/cli-plugin-vuex:  5.0.0-alpha.8 
    @vue/cli-service: 5.0.0-alpha.8 => 5.0.0-alpha.8 
    @vue/cli-shared-utils:  5.0.0-alpha.8 
    @vue/component-compiler-utils:  3.2.0 
    @vue/eslint-config-typescript: ^7.0.0 => 7.0.0 
    @vue/test-utils: ^1.1.3 => 1.1.3 
    @vue/web-component-wrapper:  1.3.0 
    eslint-plugin-vue: ^7.8.0 => 7.8.0 
    jest-serializer-vue:  2.0.2 
    typescript: ~4.2.3 => 4.2.3 
    vue: ^2.6.12 => 2.6.12 
    vue-eslint-parser:  7.6.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  16.1.2 (15.9.6)
    vue-router: ^3.5.1 => 3.5.1 
    vue-style-loader:  4.1.3 
    vue-template-compiler: ^2.6.12 => 2.6.12 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: 5.0.0-alpha.8
```

### Steps to reproduce
run vue-cli-service test:unit

### What is expected?
tests run

### What is actually happening?
@vue/cli-plugin-unit-jest/presets/typescript-and-babel not found

### PR DESCRIPTION
**Pull request by m0ksem**
Show fallback message for typescript jest preset if ts-jest is not installed.

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Underlying tools
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Other information:**
Because ts-jest is an optional peer dependency there are should be a fallback message If the module is not installed.
closes #6383

### CODE REVIEW

File: packages/@vue/cli-plugin-unit-jest/presets/typescript/jest-preset.js [hunk 1]
```diff
@@ -1,12 +1,19 @@
 const deepmerge = require('deepmerge')
 const defaultPreset = require('../default/jest-preset')
 
+let tsJest = null
+try {
+  tsJest = require('ts-jest')
```
Comment (sodatea) [inline packages/@vue/cli-plugin-unit-jest/presets/typescript/jest-preset.js:6]: Thanks! But this line should be `require.resolve` rather than `require`.
```suggestion
  tsJest = require.resolve('ts-jest')
```

**Review by sodatea — CHANGES_REQUESTED** [review]

**Review by sodatea — APPROVED** [review]
