### PR TITLE
Escape double quotes in string prompts

### LINKED ISSUE #382: Escaping for package.json
I am certain if this is a issue with vue-cli or the template, however I think the "setup questions" are asked by the cli?

My problem: I just setup a new project and followed the standard procedure:
See this

As you can see, I used double quotes inside of the Author field (for my nickname). This resulted in the following error:
image

When looking into my generated package.json, you can see that the double quotes just got copied into the `author` field:

```json
....
"author": "Pascal "Arial7" Riesinger <riesinger.pascal@gmail.com>",
  "private": true,
  "scripts": {
....
```

So my suggestion is to escape the user input before writing it to the `package.json` file.

### PR DESCRIPTION
**Pull request by Arial7**
This fixes #382.
It checks if the answer type is `string`, and if it is, `replace`s `"` with `\"`, so it can be parsed as valid JSON.

### CODE REVIEW

**Comment by posva** [comment]
Can you add a test case for this?
You can reuse one of the tests and verify that the generated package json is correct by parsing it

**Comment by Arial7** [comment]
I'm not home anymore, but I can do this tomorrow ;)

If I understood you correctly, the test should just verify that the
package.json is valid JSON?

Eduardo San Martin Morote <notifications@github.com> schrieb am Mi., 8.
März 2017, 12:06:

**Comment by posva** [comment]
Yes, so that the double quotes are escaped correctly

**Comment by Arial7** [comment]
Okay, I think that I should be able to do this :)

Eduardo San Martin Morote <notifications@github.com> schrieb am Mi., 8.
März 2017, 12:12:

**Comment by Arial7** [comment]
I just added a test to check the escaping. I tired to leave the other tests alone and add it seperately... May not be the best test, but it should do the trick 😄

File: test/e2e/test.js [hunk 1]
```diff
@@ -106,6 +122,22 @@ describe('vue-cli', () => {
...
 
+  it('generate a vaild package.json with escaped author', done => {
+    monkeyPatchInquirer(escapedAnswers)
+    generate('test', MOCK_TEMPLATE_REPO_PATH, MOCK_TEMPLATE_BUILD_PATH, err => {
+      if (err) done(err)
+
+      const pkg = fs.readFileSync(`${MOCK_TEMPLATE_BUILD_PATH}/package.json`, 'utf8')
+      try {
+        var validData = JSON.parse(pkg)
+        expect(validData.author).to.equal(escapedAuthor)
```
Comment (posva) [inline test/e2e/test.js]: Can't you just do `expect(validData.author).to.equal(escapedAnswers.author)` ?

Comment (Arial7) [inline test/e2e/test.js]: Jup, could definitively do that.... My mistake 😂

Comment (Arial7) [inline test/e2e/test.js]: Just woke up an hour ago, still not very awake

**Comment by zigomir** [comment]
LGTM 👍
