### PR TITLE
fix(lib): replace "url" module with simple string split (close #4667)

### LINKED ISSUE #4667: vue-cli-service build fails due to wrong filename since v3.10.0
### Version
4.0.5

### Reproduction link
[cli-service-bug-reproduction](https://github.com/RSeidelsohn/cli-service-bug-reproduction)

### Environment info
```
Environment Info:

  System:
    OS: Linux 4.4 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 12.7.0 - ~/.nvm/versions/node/v12.7.0/bin/node
    Yarn: 1.19.1 - ~/.yarn/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v12.7.0/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @storybook/vue:  5.2.1
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.11.0
    @vue/babel-preset-jsx:  1.1.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.1.0
    @vue/cli-overlay:  4.0.0-rc.7
    @vue/cli-plugin-babel: ^3.8.0 => 3.11.0
    @vue/cli-plugin-e2e-cypress: ^3.8.0 => 3.11.0
    @vue/cli-plugin-typescript: ^3.8.0 => 3.11.0
    @vue/cli-plugin-unit-jest: ^3.8.0 => 3.11.0
    @vue/cli-service: ^4.0.0 => 4.0.0-rc.7
    @vue/cli-shared-utils:  3.11.0 (4.0.0-rc.7)
    @vue/component-compiler-utils:  3.0.0 (2.6.0)
    @vue/preload-webpack-plugin:  1.1.0
    @vue/test-utils: 1.0.0-beta.29 => 1.0.0-beta.29
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.2.3 => 5.2.3
    jest-serializer-vue:  2.0.2
    storybook-vue-router: ^1.0.7 => 1.0.7
    typescript: ^3.4.3 => 3.6.3
    vue: ^2.6.10 => 2.6.10
    vue-class-component: ^7.0.2 => 7.1.0
    vue-cli-plugin-storybook: ^0.6.1 => 0.6.1
    vue-eslint-parser:  5.0.0
    vue-hot-reload-api:  2.3.3
    vue-jest:  3.0.5
    vue-loader:  15.7.0
    vue-meta: ^2.0.5 => 2.3.1
    vue-property-decorator: ^8.1.0 => 8.2.2
    vue-router: ^3.0.3 => 3.1.3
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
run "yarn build"

### What is expected?
Build runs through

### What is actually happening?
Command fails with exit code 1 because one file created can not be accessed:

"Error: ENOENT: no such file or directory, open '/your/path/here/dist/js/article%20page0.852bf769.js'" - the file exists, but the space between "article" and "page15" has to be escaped or written as space, not as "%20". The file system can not find it with the percent sign. This happens also on a MacBook of a colleague.

---
**I tracked the bug down to cli-service version 3.10.0 - up to 3.9.3 the build is fine, from version 3.10.0 on all versions until 4.0.5 fail with the exact same error.** ~~I might be allowed to send a copy of the repo affected to one dev for debugging purposes.~~ I have created a completely stripped down version of our repository that should enable everyone to reproduce the bug. See link in the top section.

### PR DESCRIPTION
**Pull request by RSeidelsohn**
Fixes issue #4667 by implementing the proposal https://github.com/vuejs/vue-cli/issues/4667#issuecomment-548464520 (I opened that issue and checked if this change really fixes the issue I had - it does)
Also gets rid of a node module by using simpler code for removing eventual GET parameters

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Underlying tools
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Other information:**

### CODE REVIEW

File: packages/@vue/cli-service/lib/commands/build/formatStats.js [hunk 1]
```diff
@@ -22,7 +21,7 @@ module.exports = function formatStats (stats, dir, api) {
   const isMinJS = val => /\.min\.js$/.test(val)
   assets = assets
     .map(a => {
-      a.name = url.parse(a.name).pathname
+      a.name = a.name.split(`?`)[0]
```
Comment (sodatea) [inline packages/@vue/cli-service/lib/commands/build/formatStats.js]: Please use single quotes here.
```suggestion
      a.name = a.name.split('?')[0]
```

Comment (RSeidelsohn) [reply packages/@vue/cli-service/lib/commands/build/formatStats.js]: Sure, thank you. I just noticed that backticks are being used in other places (without any need/variables), which is the only reason why I also used them.

Comment (sodatea) [reply packages/@vue/cli-service/lib/commands/build/formatStats.js]: So… seems we also need to fix these legacy codes sometime later. Thanks for spotting this!
