### PR TITLE
fix: proxy should warn when array is passed.

### LINKED ISSUE #3524: Proxy settings do not accept an array but array passes validations and fails silently
### Version
3.4.1

### Steps to reproduce
in vue config set proxy config to:
```
devServer: {
  overlay: {
    warnings: true,
    errors: true
  },
  host: '0.0.0.0',
  disableHostCheck: true,
  index: '',
  proxy:[{
    context: ['/**', '!/app.js', '!/sockjs-node/**'],
    target: 'http://localhost:8000'
  }]
}
```

### What is expected?
The http-proxy-middleware package accepts an array as a config option (https://github.com/chimurai/http-proxy-middleware#context-matching) but this is not supported by vue-cli.  Vue cli should warn the user that the array syntax is unsupported.

### What is actually happening?
No error is raised because in the prepareProxy function in prepareProxy.js typeof proxy !== 'object' is used to check that the proxy config is an object, but an array passes this test.  The typeof an Array is 'object'.

### PR DESCRIPTION
**Pull request by LinusBorg**
close #3524

### CODE REVIEW

File: packages/@vue/cli-service/lib/util/prepareProxy.js [hunk 1]
```diff
@@ -27,7 +27,7 @@ module.exports = function prepareProxy (proxy, appPublicFolder) {
   if (!proxy) {
     return undefined
   }
-  if (typeof proxy !== 'object' && typeof proxy !== 'string') {
+  if (Array.isArray(proxy) || (typeof proxy !== 'object' && typeof proxy !== 'string')) {
```
Comment (sodatea) [inline packages/@vue/cli-service/lib/util/prepareProxy.js]: There's a `\u00A0` before `(typeof proxy`

Comment (LinusBorg) [reply packages/@vue/cli-service/lib/util/prepareProxy.js]: Thanks, fixing ...
