### PR TITLE
fix(cli-service): do not log absolute baseUrl in terminal, close #2877

### LINKED ISSUE #2877: baseUrl should handle full urls
### What problem does this feature solve?
Per the docs, "The base URL your application bundle will be deployed at. This is the equivalent of webpack's output.publicPath". In the [webpack docs](https://webpack.js.org/configuration/output/#output-publicpath) it's clear full urls are valid, one of the examples is 'https://cdn.example.com/assets/'.

From the [docs for `devServer.publicPath`](https://webpack.js.org/configuration/dev-server/#devserver-publicpath-): "It is also possible to use a full URL. This is necessary for Hot Module Replacement." The point about HMR is clear when you look at [issue 2525](https://github.com/vuejs/vue-cli/issues/2525#issuecomment-421573105), where the HMR is using the wrong URL for updates.

Setting `baseUrl` to a full URL results in a message from `vue-cli-service serve` such as:

>   App running at:
>  - Local:   https://localhost:8443/https://other-address.local/

It *does* fix the HMR issue, since it plumbs down correctly, but `vue-cli` isn't treating it as the full URL that it is.

If `baseUrl` is the equivalent of webpack's `output.publicPath` as the docs say, then it must correctly handle full URLs. Otherwise they are not equivalent.

### What does the proposed API look like?
N/A

### PR DESCRIPTION
**Pull request by jkzing**
#2877

### CODE REVIEW

File: packages/@vue/cli-service/lib/commands/serve.js [hunk 1]
```diff
@@ -89,7 +90,7 @@ module.exports = (api, options) => {
       protocol,
       host,
       port,
-      options.baseUrl
+      isAbsoluteUrl(options.baseUrl) ? '/' : options.baseUrl
```
Comment (LinusBorg) [inline packages/@vue/cli-service/lib/commands/serve.js]: Won't that break for `baseUrl: http://localhost:8081/someBasePath/` ?

Comment (jkzing) [reply packages/@vue/cli-service/lib/commands/serve.js]: Set baseUrl to `http://localhost:8081/someBasePath/` doesn't mean to start the dev-server on `localhost:8081`, the dev-server would still be started on `${host}:${port}`.

Comment (LinusBorg) [reply packages/@vue/cli-service/lib/commands/serve.js]: Sure, but doesn't the console now say " go to host: port/" even though people would have to go to "localhost:port/baseurl"?

I'm honestly confused because paths and hosts in webpack can be confusing as hell to me

Comment (jkzing) [reply packages/@vue/cli-service/lib/commands/serve.js]: Consider those two cases here:

1. Asset files (js/css/img) are served by `webpack-dev-server` (eg. localhost:8080), and user uses a reverse proxy to access the **html** (eg. localhost:3000/app/). In this case, `baseUrl` should be set to `http://localhost:8080/`, but user need to open `http://localhost:3000/app/` in browser.

2. Asset files (js/css/img) are served by `webpack-dev-server` (eg. localhost:8080), and user uses a reverse proxy to access the **asset files** (eg. localhost:3000/assets/). In this case, `baseUrl` should be set to `http://localhost:3000/assets/`, and user need to go to `http://localhsot:8080` in browser.

What I want to say is, we cannot infer which url should user open in browser if user set `baseUrl` to a absolute url. What we can do is tell user "we have started your dev-server on localhost:8080"... 

And, yes it is confusing. 😂

Comment (LinusBorg) [reply packages/@vue/cli-service/lib/commands/serve.js]: Awesome, that was very helpful. Thanks.
