### PR TITLE
fix: add missing package keys to the sort array (issue #3509)

### LINKED ISSUE #3509: extendPackage changes the order of the keys
### Version
3.4.1

### Reproduction link
[https://github.com/elevatebart/test-vue-lib](https://github.com/elevatebart/test-vue-lib)

### Environment info
```
MacOS, node 10, yarn 1.13
```

### Steps to reproduce
When using the followin code in my plugin, I get changes on the order of keys in packages.json. It is very unsetling for users.
```js
api.extendPackage({
    scripts: {
      styleguide: 'vue-cli-service styleguidist',
      'styleguide:build': 'vue-cli-service styleguidist:build'
    }
  })
```

### What is expected?
I expect the extendPackages touches only what it is intended to and leves the rest alone.

### What is actually happening?
The folloing keys are moved to the end of the file:
main, files, unpkg

---
Found while inverstigating https://github.com/vue-styleguidist/vue-cli-plugin-styleguidist/issues/34

### PR DESCRIPTION
**Pull request by elevatebart**
closes #3509

### CODE REVIEW

File: packages/@vue/cli/lib/Generator.js [hunk 1]
```diff
@@ -181,9 +181,13 @@ module.exports = class Generator {
       'private',
       'description',
       'author',
+      'main',
+      'unpkg',
```
Comment (LinusBorg) [inline packages/@vue/cli/lib/Generator.js]: We could also inlcude the `jsDelivr` field if we add `unpkg`
```suggestion
      'jsDelivr',
      'unpkg',
```

File: packages/@vue/cli/lib/Generator.js [hunk 2]
```diff
@@ -181,9 +181,13 @@ module.exports = class Generator {
...
+      'files',
       'scripts',
```
Comment (LinusBorg) [inline packages/@vue/cli/lib/Generator.js]: I would prefer for the scripts to be above the file-related fields (main, files etc.), because as a developer I have to look for those quite a lot.

This is of course subjective - other's feelings about this?

File: packages/@vue/cli/lib/Generator.js [hunk 3]
```diff
@@ -181,9 +181,13 @@ module.exports = class Generator {
       'private',
       'description',
       'author',
+      'main',
```
Comment (LinusBorg) [inline packages/@vue/cli/lib/Generator.js]: While we are at it, there are some other related fields:
```suggestion
      'main',
      'module',
      'js:next',
      'browser',
```

File: packages/@vue/cli/lib/Generator.js (hunk 2 above)
Comment (andreasvirkus) [reply packages/@vue/cli/lib/Generator.js]: Agreed. This is also a well-established best practise imo

Comment (elevatebart) [reply packages/@vue/cli/lib/Generator.js]: You guys are absolutely right. 
Great remarks. 
Hope my  fixes are AOK ;)
