### PR TITLE
fix: fix several bugs in the PWA plugin UI, make it usable again

### LINKED ISSUE #4903: 4.1.1使用项目管理配置pwa，无法保存
### Version
4.1.1

### Reproduction link
[https://github.com/playfulhd/ISSUE](https://github.com/playfulhd/ISSUE)

### Environment info
```
  System:
    OS: Windows 7 6.1.7601
    CPU: (4) x64 Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz
  Binaries:
    Node: 12.13.0 - D:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.12.0 - D:\Program Files\nodejs\npm.CMD
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1. vue ui 创建项目
2. 修改pwa配置，无任何保存操作

### What is expected?
使用pwa，修改配置

### What is actually happening?
无保存操作

---
如果没有问题则忽略本次提问，可以的话解答一下。

### PR DESCRIPTION
**Pull request by sodatea**
closes #4903

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Underlying tools
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Other information:**

### CODE REVIEW

File: packages/@vue/cli-plugin-pwa/ui.js [hunk 1]
```diff
@@ -58,7 +64,12 @@ module.exports = api => {
             message: 'org.vue.pwa.config.pwa.backgroundColor.message',
             description: 'org.vue.pwa.config.pwa.backgroundColor.description',
             default: '#000000',
-            value: data.manifest && data.manifest.background_color,
+            value:
+              (data.vue &&
+                data.vue.pwa &&
+                data.vue.pwa.manifestOptions &&
+                data.vue.pwa.manifestOptions.background_color) ||
+              (data.manifest && data.manifest.background_color),
```
Comment (Akryum) [inline packages/@vue/cli-plugin-pwa/ui.js]: We really need optional chaining 😅

Comment (sodatea) [reply packages/@vue/cli-plugin-pwa/ui.js]: 👀Time to use TypeScript for every project!
